### ISSUE TITLE
Is it normal that generation of density map takes long to complete?

### ISSUE THREAD

**Issue by Sreerag-ibtl** [Neerajj9/CSRNet-keras#21]
I am running the experiment on colab. The tqdm progress bar shows about 8+ hours for completion. Is it too long or a normal time?

**Comment by saahil1292** [comment]
> I am running the experiment on colab. The tqdm progress bar shows about 8+ hours for completion. Is it too long or a normal time?

Hi, yes it is quite normal to take the running time more than 8+ hrs. What you can do is, you can create an exception handling and whenever an error occurs, it stores the state of the program and resumes from where it left.

Please find below the code to the above workaround

from tqdm import tqdm

try:
  i=0
  temp = []
# Code will run till all the files are processed (Len of the files in all folder)
  for img_path in tqdm(list_of_images(path_sets)):

    if os.path.exists('img_paths.pickle'):
      with open('img_paths.pickle', 'rb') as f:
        temp, pkl_path = pickle.load(f)
        if img_path == pkl_path:
          continue

    if img_path not in temp:

      # load matlab file and replaces name with the values defined
      mat = io.loadmat(img_path.replace('.jpg', '.mat').replace('images', 'ground_truth').replace('IMG_', 'GT_IMG_'))
      # read image
      img = plt.imread(img_path)
      # create a zero size matrix of image
      k = np.zeros((img.shape[0], img.shape[1]))
      # takes the first element from the image keys and values
      gt = mat['image_info'][0,0][0,0][0]

      # generate Hot encoded matrix of sparse matrix
      for i in range(0,len(gt)):
        if int(gt[i][1]) < img.shape[0] and int(gt[i][0]) < img.shape[1]:
          k[int(gt[i][1]), int(gt[i][0])] = 1

      # generate density map
      k = gaussian_filter_density(k)

      # file path to save the density map of all images
      file_path = img_path.replace('.jpg', '.h5').replace('images', 'ground')
  
      # write the data into the file
      with h5py.File(file_path, 'w') as hf:
              hf['density'] = k

      temp.append(img_path)

    else:

      continue

      #print(img_path) 

except (KeyboardInterrupt, SystemError, RuntimeError):
  with open('img_paths.pickle', 'wb') as f:
    pickle.dump([temp,img_path], f)

**Comment by Sreerag-ibtl** [comment]
Thank you @saahil1292
