### ISSUE TITLE
0%|          | 0/1198 [00:00<?, ?it/s]

### ISSUE THREAD

**Issue by SherlockHua1995** [Neerajj9/CSRNet-keras#3]
hello,thanks for your opensource.
When I preprocess the  dataset ,and the progress bar doesn't move forward.
And there are indeed 1198 items.

**Comment by SherlockHua1995** [comment]
And would you plz give me some information about the keras version and tensorflow-gpu version?
Thanks.

**Comment by Neerajj9** [comment]
Hello @SherlockHua1995  thank you for pointing this out. For testing purpose I had put a break statement in the loop. That is why the progress bar is constant on 1 and only 1 ground truth is being generated. Removing the break statement in the `Preprocess.ipynb will indeed solve the problem. Check it out now.

**Comment by Neerajj9** [comment]
The libraries and versions have been updated

**Comment by SherlockHua1995** [comment]
Thanks a lot for your timely reply.
I have found that you removed the "break" command.

from tqdm import tqdm

i = 0
for img_path in tqdm(img_paths):
        
    
    # Load sparse matrix
    mat = io.loadmat(img_path.replace('.jpg','.mat').replace('images','ground_truth').replace('IMG_','GT_IMG_'))
    
    #Read image
    img= plt.imread(img_path)
    
    # Create a zero matrix of image size
    k = np.zeros((img.shape[0],img.shape[1]))
    
    gt = mat["image_info"][0,0][0,0][0]
    
    #Generate hot encoded matrix of sparse matrix
    for i in range(0,len(gt)):
        if int(gt[i][1])<img.shape[0] and int(gt[i][0])<img.shape[1]:
            k[int(gt[i][1]),int(gt[i][0])]=1
    
    # generate density map
    k = gaussian_filter_density(k)
    
    # File path to save density map
    file_path = img_path.replace('.jpg','.h5').replace('images','ground')
    
    #break
    with h5py.File(file_path, 'w') as hf:
            hf['density'] = k

I tried this operation but the situation is still the same.

**Comment by SherlockHua1995** [comment]
@Neerajj9 Hello ,I tried but not it didn't work.
0.0

**Comment by Neerajj9** [comment]
The code does not have any bugs. We have tested the code and it works fine. It takes a lot of processing power to form heatmaps and thus the progress bar moves ahead slowly. There must be some other issue with respect to your local system. Please check.

**Comment by SherlockHua1995** [comment]
0%|          | 0/1198 [00:00<?, ?it/s]

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-8-3d0091f106e9> in <module>
     28 
     29 
---> 30     with h5py.File(file_path, 'w') as hf:
     31             hf['density'] = k

~/.local/lib/python3.5/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    310             with phil:
    311                 fapl = make_fapl(driver, libver, **kwds)
--> 312                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    313 
    314                 if swmr_support:

~/.local/lib/python3.5/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    146         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
    147     elif mode == 'w':
--> 148         fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
    149     elif mode == 'a':
    150         # Open in append mode (read/write).

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.create()

OSError: Unable to create file (unable to open file: name = 'data/part_A_final/train_data/ground/IMG_65.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

**Comment by SherlockHua1995** [comment]
Sorry for bothering you.0.0
I think this error is not caused by my local system environment .

unable to open file: name = 'data/part_A_final/train_data/ground/IMG_65.h5'

The .h5 file have not by generated and thus cannot be opened.
Any advice?Thank you .

**Comment by 3rdnightbaron** [comment]
I too face the same issue as @SherlockHua1995 has faced. @Neerajj9 please have a look into it

I have installed all the dependencies and still facing the same issue.

Thanks in advance :)

**Comment by 3rdnightbaron** [comment]
@SherlockHua1995 I was able to resolve it. As @Neerajj9 mentioned there is no bug in the code. You just have to create a folder named ground in the part_A_final/train_data (and other corresponding folders) the h5py can create a .h5 file. But it cannot create a folder. Hence it is giving cannot create file error because it is not able to find any folder with the name ground.
