### ISSUE TITLE
leafsize = 2048

### ISSUE THREAD

**Issue by norahik** [Neerajj9/CSRNet-keras#7]
hello,

i was wondering, is there a special reson for choosing leafsize = 2048 for the KDTree?

what if the # of data we are sorting in this tree are less than 2048? aren't they going to be in one branch?

**Comment by aditya-malte** [comment]
A larger leaf size rather than the default (30), allows for a faster computation of queries, this is because fewer nodes can be constructed.
Note: The leaf size only denotes the point at which the algorithm switches to brute force.
