### ISSUE TITLE
Inference time to test a image

### ISSUE THREAD

**Issue by SherlockHua1995** [Neerajj9/CSRNet-keras#8]
Hello, 
I have tried to make sure the inference time of testing a single image and I found that it took too much time.
import time
    start = time.clock()
    ans,img,hmap = predict('/home/xd/workspace/CSRNet-keras/test_images/IMG_153.jpg')
    elapsed = (time.clock() - start)
    print("Time used:",elapsed)

output: Time used: 6.246331
The unit should be S.

SO it's quiet time-expensive ,isn't it?

**Comment by aditya-malte** [comment]
Hello,
Undoubtedly, it is a very large network encompassing more than 10 layers. So, I think that the inference time is justified.
Although, you could reduce the image resolution yo help speed up the inference phase.
Thanks

**Comment by SherlockHua1995** [comment]
Thanks for your advice.
Reducing the resolution could degrade the precision?
The inference time is decided by the image size, and the network structure and any other factor?

**Comment by aditya-malte** [comment]
Hello,
For your first question: not really as long as the image is intelligible.
2)The inference time is also dependant on hardware and strongly correlates with image size.
Thank you.

**Comment by aditya-malte** [comment]
It depends on how much are you ready to sacrifice accuracy for a lower inference time.
So you will probably have to figure out the image resolution on your own.
